<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Checkout\Block\Onepage\Link;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Link $block */

if (!$block->isPossibleOnepageCheckout()) {
    return '';
}
?>
<div x-data="elgentosStickyCartProceedButton">
    <a @click.prevent.stop="navigateInteract"
        href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getCheckoutUrl())) ?>"
        title="<?= $escaper->escapeHtmlAttr(__('Proceed to Checkout')) ?>"
       class="btn btn-primary text-lg font-medium py-4 px-10 fixed bottom-0 left-0 right-0 w-full z-50
           bg-primary text-center text-white rounded-t-lg lg:rounded-b-lg rounded-b-none lg:static
           lg:w-auto lg:px-10 lg:py-4 justify-center text-center"
        id="checkout-link-button"
    >
        <?= $escaper->escapeHtml(__('Proceed to Checkout')) ?>
    </a>
</div>
<script>
    function elgentosStickyCartProceedButton() {
        return {
            navigateInteract() {
                this.$dispatch(
                    'toggle-authentication',
                    {
                        url:
                            this.$el.href
                    }
                );
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('elgentosStickyCartProceedButton', elgentosStickyCartProceedButton), {once: true});
</script>
<?php $hyvaCsp->registerInlineScript() ?>

